[project]
name = "mcp-use-demo"
version = "0.1.0"
description = "Creating a chatbot with browser automation capabilities"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-groq>=0.3.2",
    "mcp-use>=1.2.8",
    "python-dotenv>=0.20.0"
]
